owner: JesseHoekema # GitHub username
repo: jessehoekemacom-upptime # GitHub repository name
user-agent: JesseHoekema
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
status-website: # Status website (optional)
  baseUrl: /jessehoekemacom-upptime
  name: Upptime # Status website title
